name: Release
on:
  release:
    types: [published, edited]

jobs:
  tags:
    name: Update tags
    runs-on: windows-2022
    steps:
      - uses: Actions-R-Us/actions-tagger@v2
        with:
          publish_latest_tag: true
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'published' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: echo "filename=clear-calendar-${{ github.event.release.tag_name }}.zip" >> $GITHUB_ENV
      - uses: thedoctor0/zip-release@0.7.1
        with:
          filename: ${{ env.filename }
          path: dist
      - uses: nanoufo/action-upload-artifacts-and-release-assets@v1.7
        with:
          path: ${{ env.filename }}
          if-no-files-found: error
          upload-release-files: true
          release-upload-url: ${{ github.event.release.upload_url }}
          filename: clear-calendar-${{ github.event.release.tag_name }}
      - uses: Klemensas/chrome-extension-upload-action@$VERSION
        with:
          refresh-token: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          file-name: ${{ env.filename }}
          app-id: 'igokphnjmioaekmakimhfopjkleneooa'
          publish: true
